### ISSUE TITLE
The best way to handle MySQL connection in master.

### ISSUE THREAD

**Issue by shtse8** [huyanping/simple-fork-php#12]
If I have to connect to database in master process, and according to the records to execute process in FixedPool, do you have any suggestions?
As you know, sharing connection is dangerous, and it will be closed when the child is end. I don't know how to do using your library if I need the connection in master process.

**Comment by white-poto** [comment]
A better way to manage mysql connections is create a connection for each process. You can do it like this:
```php
$connection = [];
$connection[getmypid()] = new Connection();
```

**Comment by shtse8** [comment]
Yes, of course creating a connection for each process. But now my I have to create connection for parent process. Do you have any ideas?

**Comment by white-poto** [comment]
If you don't want to share connections, you can create the connections after `pcntl_fork()`.

**Comment by shtse8** [comment]
```php
use \Jenner\SimpleFork\Pool;
use \Jenner\SimpleFork\FixedPool;
use \Jenner\SimpleFork\ParallelPool;
use \Jenner\SimpleFork\Process;
use \Jenner\SimpleFork\Runnable;

class TestRunnable implements Runnable 
{
	private $id = 0;

	public function __construct($id) {
		$this->id = $id;
	}
	
    public function run()
    {
		// do something
    }
	
}

$db = new DB(/* Login Credential */);
$pool = new FixedPool(2);

$stmt = $db->query("SELECT `id` FROM `table`");
while($row = $stmt->fetch() ) {
    $pool->execute(new Process(new TestRunnable($row['id'])));
}
$db->query("UPDATE `table2` SET `done` = `done` + 1");
$pool->wait();
```

If I want to do something like this with master MySQL connection, do you have any good suggestions?

**Comment by white-poto** [comment]
It is not a good idea that creating sub processes when fetching database. You can do it after closing the connection. Like this:
```php
$data = $conn->fetchAll();
$conn->close();
foreach($data as $record) {
    // create sub process
}
```

**Comment by shtse8** [comment]
How about if the result set is more than 5G ( >3M records )?

**Comment by white-poto** [comment]
The `execute` method will not block after the pool size reached the fixed size, so all the data(5G and >3M records) will load into the memory. 

I guess your problem is that you want to access the data iteratively. A better way is that you can create a producer and some consumers in sub processes and communicate with redis-queue. You can control the queue size, you can stop produce messages when the queue size is too big and you can control the consumer's process count. It is not a good idea that produce message in the master process.

There is some examples in the`example` directory.

**Comment by shtse8** [comment]
Yes, I understand, but for my best educated knowledge, althought the data
will loaded into mempry but it is not a real memory usage but is a shared
memory usage until the data set is modified in sub process.

How about if I want to execute only if having any jobs and sharing large
data set for my sub processes? that means there is a large data set which I
don't want to load it in child processes, and producing child process from
database results.

2017年4月3日 上午10:25，"Jenner" <notifications@github.com>写道：

**Comment by shtse8** [comment]
Yes, I understand, but for my best educated knowledge, although the data
is loaded into memory but it is not a real memory usage but is a shared
memory usage until the data set is modified in sub process.

How about if I want to execute only if having any jobs and sharing large
data set for my sub processes? that means there is a large data set which I
don't want to load it in child processes, and producing child process from
database results.

This is my situation:
- I have to write a server keeping maintaining my articles ranking, that's why I need to load all articles in PHP in master.
- The score calculation is very complicated which takes about 1 minute to process.
- The score calculation is based on requests, need to do and fork a process to do.
- The article dataset needs to be updated and synced with database

So I have created a pool and made a server. In each turn, loads all articles from database, getting ranking requests from database, forking based on the request and limit the sub-processes using fixed pool, wait all sub-process finish to do next turn.

Example:
```php
// expected to wait if reaching the max sub-processes in the pool, 
// but can't test at this moment due to the exception I have reported in another issue.
$pool = new FixedPool(5); // Fix the pool to 5,

while(true) { // Server Mode

	$articles = []; // Large Dataset ( > 5G memory, and keep increasing, )
	$stmt = $db->query("SELECT * FROM `article`"); // > 1min processing time, that's why I don't want to do it in each subprocess
	while( $row = $stmt->fetchAll() ) {
		$articles[] = $row;
	}

	// Getting jobs from database ( to calculate rankings )
	$stmt = $db->query("SELECT * FROM `jobs` WHERE `valid` = 1");
	while( $row = $stmt->fetchAll() ) {
		$pool->execute(new Process(new JobRunnable($row, $articles)));
	}
	$pool->wait();

}
```

Troubles:
1.  It's hard to execute consumer process in producer process in the master pool.
2. Large dataset is hard to communicate using shared memory
