### ISSUE TITLE
the multiprocessing speed is not ideal

### ISSUE THREAD

**Issue by chengxueming** [huyanping/simple-fork-php#13]
I run the example in simple-fork-php/examples/redis-queue/

> time php Producer.php
> time php Consumer.php

but only $forkCount equal to one i got max speed
` for($i = 0; $i< $forkCount; $i++) {
     $consumer = new Consumer();
     $pool->execute($consumer);
 }`
`real    0m18.212s
user    0m2.868s
sys    0m2.910s`
if fork count equal to five
`real    0m58.395s
user    0m25.212s
sys    0m33.047s`
so it cant make my code fast even slow much more
what is wrong with me?

**Comment by white-poto** [comment]
这个问题有点复杂，还是用中文回答你吧。
虽然你的程序是多进程并行的，但是redis是单线程的。所以在客户端处理消息非常快的时候，但进程的消费者是有可能比多进程的消费者要快一些的，因为多进程间的资源互斥，会消耗一些时间。

如果Comsumer.php中的逻辑不是echo，打个比方，如果队列的内容是url，而消费者的工作是请求这些url，这时，多进程的消费者会占据明显优势。

**Comment by chengxueming** [comment]
非常感谢，确实很好用。我用这个程序给公司发微信模板消息，之前1700多条要20分钟，现在开了10个进程3分钟就发了6000条

**Comment by white-poto** [comment]
客气哈
