### ISSUE TITLE
Shared memory between same process types

### ISSUE THREAD

**Issue by Ragazzo** [huyanping/simple-fork-php#2]
Currently as i see it is possible that two parallel processes will override each other changes since they will look at same shared memory according this [code](https://github.com/huyanping/simple-fork-php/blob/master/src/Cache/SharedMemory.php#L70). I think it is better to use a a process PID since it is unique per given machine. 

@huyanping what are your thoughts on this one? Also can you elaborate why you are using file there?

**Comment by huyanping** [comment]
All cache classes implements the CacheInterface. I thought that the cache object shouldn't care about how different processes use it to add, get or update the data. The SharedMemoryCache is just like RedisCache, so you can modify the value in different processes when you use any of the cache classes. If you want to keep different processes' cache in different namespace, you can extend the cache class to do it.

I am not sure which file you are talking about. I guess it is about this [code](https://github.com/huyanping/simple-fork-php/blob/master/src/Cache/SharedMemory.php#L41), this file is used to make a IPC key which is required for initializing the shared memory resouce

**Comment by Ragazzo** [comment]
Ok, thanks for clarifying this one
