### ISSUE TITLE
require(H:\www\simple-fork-php\vendor\autoload.php): failed to open stream: No such file or directory in H:\www\simple-fork-php\examples\simple.php on line 9

### ISSUE THREAD

**Issue by StevenFather** [huyanping/simple-fork-php#4]
@huyanping require(H:\www\simple-fork-php\vendor\autoload.php): failed to open stream: No such file or directory in H:\www\simple-fork-php\examples\simple.php on line 9
没有vendor目录呀

**Comment by StevenFather** [comment]
@huyanping

**Comment by huyanping** [comment]
composer update

**Comment by StevenFather** [comment]
win下不能用的吧？悲剧。。。

**Comment by huyanping** [comment]
win下没有pcntl扩展
